#!/usr/bin/env php
<?php require __DIR__ . '/vendor/autoload.php';
$playlist_id = isset($argv[1]) ? $argv[1] : "none set";


echo $playlist_id;
/*use GuzzleHttp\Client;

$client = new Client([
    // Base URI is used with relative requests
    'base_uri' => 'http://httpbin.org',
    // You can set any number of default request options.
    'timeout'  => 2.0,
]);*/

